### ISSUE TITLE
Feature Request: accessing the currentPhotoIndex in a subclass of PhotosViewController

### ISSUE THREAD

**Issue by deepmode** [alexhillc/AXPhotoViewer#13]
Hi Alex,
I am trying to do a custom share action button via a subclass of PhotosViewController. Is there a way to access the currentPhotoIndex directly in a  subclass of PhotosViewController?

Eric

**Comment by alexhillc** [comment]
Hi @deepmode, these properties were exposed in c80fd1cccd9ceb1a5cf0f2ebb99540fe4f17ba90

**Comment by deepmode** [comment]
Thanks! 👍
