### ISSUE TITLE
page #  at the top cover up by "sensor housing" area in iPhone X 

### ISSUE THREAD

**Issue by deepmode** [alexhillc/AXPhotoViewer#14]
Hi Alex,

Please ignore my previous comment, I was trying to hide the status bar and the cause the issue. 
Issue resolved by disable the hiding of status bar.

> Just test out the AXPhotoViewer running in Simulator for iPhone X and notice that the page indicator no. at the top ( in full screen mode) fully covered by the new "sensor housing" area in iPhone X. Could you take a look? 

Eric

**Comment by alexhillc** [comment]
Fixed in ce0ba810a2268a2c8365ba3d8eb24929d5ee73cc.
