### ISSUE TITLE
ios 8?

### ISSUE THREAD

**Issue by drmarkpowell** [alexhillc/AXPhotoViewer#16]
Would it be straightforward to walk the minimum iOS version back to 8.0? For this and for AXStateButton? I've got an application in mind that could use a cool image gallery like this but I'd like to target iOS 8 as well.

**Comment by alexhillc** [comment]
Hey @drmarkpowell, realistically, this shouldn't be too hard. I don't have a lot of free time at the moment, but I'll see what I can do

**Comment by drmarkpowell** [comment]
Do you take pull requests? Maybe I could contribute

-Mark

**Comment by alexhillc** [comment]
Hey @drmarkpowell, I saw your pull request and I looked it over - but at the time I had already made those same changes in my branch. In any case, the library now supports iOS as of a83b012d57377bbe489d20ce8831804188be1844. :)
