### ISSUE TITLE
Can't find with pod search

### ISSUE THREAD

**Issue by kevinstier** [alexhillc/AXPhotoViewer#2]
Hello!
First of all I would like to say that this photo viewer looks awesome! Way to go!
But if I want to add this library using my podfile, it gives me the following error:
`Unable to find a specification for "AXPhotoViewer"`

Also, when I use
`pod search AXPhotoViewer`
it returns the following:
`Unable to find a pod with name, author, summary, or description matching "AXPhotoViewer"`

Am I doing something wrong or can I just not install this library using pods?

**Comment by alexhillc** [comment]
Hi @kevinstier, this is most likely an issue with your podspec repo being out of date. You should try to `pod repo update` before `pod search AXPhotoViewer`. Let me know if this does not help!
