### ISSUE TITLE
" url = nil"  does not seem to work.

### ISSUE THREAD

**Issue by eastswift** [alexhillc/AXPhotoViewer#25]
To insert an image of an asset, do the following:     

   for i in 0 ..< images.count - 1   {
            manager.requestImage(for: images[i],
                                 targetSize: CGSize(width: 100, height: 100.0),
                                 contentMode: .aspectFill,
                                 options: nil) { (result, _) in
                                    print(result)
                                   let resultphoto = Photo(image: result, url: nil)
                                    self.photos.append(resultphoto)             
            }

I have obviously put nil in the url, but I keep trying to download it. The image is imported from the asset.

       self.urlSession.dataTask(with: self.photos[indexPath.row].url!) { [weak self] (data, response, error) in
            guard let uData = data else {
                return
            }   

I get an error here.

**Comment by alexhillc** [comment]
Hey @eastswift, thanks for the report. I’ll take a look at this when I get some time!

**Comment by alexhillc** [comment]
This looks like it was simply a bug in the example project, which I had thrown together very sloppily to test out the framework. Sorry about that! Fixed in the latest commit.
