### ISSUE TITLE
internalTitle localization in PhotosViewController

### ISSUE THREAD

**Issue by DarkwingXL** [alexhillc/AXPhotoViewer#31]
Hi,
There is a small fix in fileprivate func updateOverlay(for photoIndex: Int)  

517       self.overlayView.internalTitle = NSLocalizedString("\(photoIndex + 1) of \(self.dataSource.numberOfPhotos)", comment: "")

It must be somelike ...

self.overlayView.internalTitle = "\(photoIndex + 1) " + NSLocalizedString("of", comment:"") +  " \(self.dataSource.numberOfPhotos)"

... to get easy localized version. Or you can use String.localizedStringWithFormat to cover some difficult cases like Arabic language and so on.

**Comment by alexhillc** [comment]
Hey @DarkwingXL, thanks for the report -- I'll have this fixed in the next release

**Comment by alexhillc** [comment]
This is fixed in the latest commit, closing out this issue.

**Comment by abdullahumer** [comment]
I was facing the same issue. 

The line 
`String.localizedStringWithFormat("%d of %d", photoIndex + 1, self.dataSource.numberOfPhotos)`
was not working.

I changed it to
`String.localizedStringWithFormat(NSLocalizedString("%d of %d", comment: ""), photoIndex + 1, self.dataSource.numberOfPhotos)`
and it worked.

I have this in my `Localized.strings` file
`"%d of %d" = "%d من %d";`
