### ISSUE TITLE
How to hide the share icon in the photo viewer?

### ISSUE THREAD

**Issue by chrisvoronin** [alexhillc/AXPhotoViewer#32]
Hi Alex,

Just let me say this first... very awesome library, saved me a ton of time.  Thank you for making this and sharing this.  Using Kingfisher loader too.

One quick question I have, is there an easy way to hide the share icon?  I didn't see some option when I looked around.

Thank you,

Chris

**Comment by alexhillc** [comment]
Hey @chrisvoronin, this should be possible by setting:
`PhotosViewController.overlayView.rightBarButtonItem = nil`

**Comment by bizibizi** [comment]
@alexhillc is there any way to replace the icon?
        photosViewController.overlayView.leftBarButtonItem?.image = UIImage(named: "close-icon")
 does not work

**Comment by bizibizi** [comment]
And I need to remove Share as well, but this code does not work 😭@alexhillc

**Comment by alexhillc** [comment]
Hey @bizibizi, in earlier versions of AXPhotoViewer (1.2.10) the overlay was instantiated with the rest of the views, which made it inconvenient to customize it before presenting the view controller. To get around this, simply load the view before customizing the pager:

```swift
photosViewController.loadViewIfNeeded()
photosViewController.overlayView.rightBarButtonItem = nil
```

As for the close button, you will have to subclass the `PhotosViewController` and override `closeBarButtonItem`, returning a `UIBarButtonItem` with a custom image. You can leave the target and action of the `UIBarButtonItem` nil (the pager will set these manually). That should get the behavior that you are expecting.

However, I do recommend updating your project to Swift 4! With the Swift 4 update came many key iOS 11 features, including safe area insets.

**Comment by bizibizi** [comment]
Yes, this works, thank you! And how can I add share button to the bottom (with custom image preferable). I am looking on the code sample but looks like 1.2.10 does not have “bottomStackContainer” to do that: 

     photosViewController.overlayView.bottomStackContainer.insertSubview(bottomView, at: 0)
        
And how can I attach “target and action” to that share button?
