### ISSUE TITLE
Memory leak and retain cycles

### ISSUE THREAD

**Issue by almatri** [alexhillc/AXPhotoViewer#4]
When the photosViewController is presented and then dismissed and then presented again many times it keep retain cycles and leaks in memory as shown below 

From the second time it is presented and so on it keep leaking memory

![screen shot 2017-08-03 at 4 00 44 pm](https://user-images.githubusercontent.com/17082327/28923074-5ea7697e-7865-11e7-9b19-6af3ae1f3a2f.png)

**Comment by alexhillc** [comment]
Hi @almatri, thanks for the report. I'll take a look at it later today.
