### ISSUE TITLE
Swipe to dismiss 

### ISSUE THREAD

**Issue by gersonjanhuel** [alexhillc/AXPhotoViewer#40]
Hi, awesome lib!!! 

Can you implement "swipe down to dismiss" the AXPhotosViewController  ?

**Comment by alexhillc** [comment]
Hey @gersonjanhuel, swipe to dismiss behavior is already available. Check out AXTransitionInfo for customization

**Comment by gersonjanhuel** [comment]
is there any official documentation to use the lib ? :)

**Comment by alexhillc** [comment]
The closest thing to official documentation would be the `README`
Otherwise, all public API is fairly well documented (there is no generated documentation, but there are swiftdocs) -- it should be pretty easy to dive into AXTransitionInfo and see what is needed
