### ISSUE TITLE
1.6.1 build failed, 17 issues

### ISSUE THREAD

**Issue by Hardtack1** [alexhillc/AXPhotoViewer#43]
1.5.0 worked fine.
1.6.1 gives 17 errors.

Environment
- swift 4.0
- target iOS 10.0 

I guess I need to update to swift 4.2 too.
Thanks for your effort on this amazing photo viewer.

![screen shot 2018-09-23 at 12 26 02 pm](https://user-images.githubusercontent.com/24969226/45931474-e453db80-bf2b-11e8-9eef-e31c816c2c55.png)

**Comment by alexhillc** [comment]
Hey @Hardtack1, v1.6.0 introduced Swift 4.2 support - in order to use the photo viewer past v1.6.0, you need to update your project to Swift 4.2.

**Comment by Hardtack1** [comment]
Ok, thanks!
