### ISSUE TITLE
Customising the actionBarButtonItem and closeBarButtonItem via subclassing the PhotosViewController

### ISSUE THREAD

**Issue by deepmode** [alexhillc/AXPhotoViewer#6]
I was trying to override the actionBarButtonItem and closeBarButtonItem (just for the look and feel) via subclassing the PhotosViewController.  The Swift compiler have this warning "Overriding non-open var outside of its defining module". To get this working, I have to change the method declaration from public to open. I wonder if this the only option for just changing the look and feel.

**Comment by alexhillc** [comment]
Hi @deepmode, thanks for the report. All exposed overrideable variables should have the ‘open’ qualifier. If they don’t, it’s a mistake on my part. I can fix this later today and push out a new release.

**Comment by alexhillc** [comment]
Fixed in: 51073b36564813b96dd275a56241bbf629c0f156

**Comment by deepmode** [comment]
Thanks!
